# Generated by Django 3.2.4 on 2021-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(verbose_name='Telegram User Identification Number')),
                ('UserName', models.TextField(verbose_name='Telegram User Name')),
                ('UserFullName', models.TextField(verbose_name='Telegram User Full Name')),
                ('TimeStamp', models.DateTimeField(verbose_name='Date')),
                ('StartDate', models.DateTimeField(verbose_name='Start Time of Work')),
                ('EndDate', models.DateTimeField(verbose_name='End Time of Work')),
            ],
            options={
                'verbose_name': 'Employee Attendance Information',
            },
        ),
    ]
